/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomwarjava;

import component.Unity;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Jonathan Germain
 */
public class gameUI extends javax.swing.JFrame {
    
    private Player playerRed;
    private Player playerBlue;
    /**
     * Creates new form gameUI
     */
    public gameUI() {
        initComponents();
        this.playerRed = new Player(10,Player.TEAM_RED, "redPlayer");
        this.playerBlue = new Player(10,Player.TEAM_BLUE, "bluePlayer");  
        this.spawBlue.setPlayer(this.playerBlue);
        this.spawnRed.setPlayer(this.playerRed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unitiesProgessBar2 = new component.UnitiesProgessBar();
        spawBlue = new component.House();
        spawnRed = new component.House();
        house7 = new component.House();
        house6 = new component.House();
        house5 = new component.House();
        house4 = new component.House();
        house3 = new component.House();
        house2 = new component.House();
        house1 = new component.House();
        jButton1 = new javax.swing.JButton();
        map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mushroom War Java Project");
        setMaximumSize(new java.awt.Dimension(1095, 610));
        setMinimumSize(new java.awt.Dimension(1095, 610));
        setResizable(false);
        setSize(new java.awt.Dimension(1095, 610));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(1095, 610));
        jPanel1.setMinimumSize(new java.awt.Dimension(1095, 610));
        jPanel1.setLayout(null);
        jPanel1.add(unitiesProgessBar2);
        unitiesProgessBar2.setBounds(410, 0, 300, 15);
        jPanel1.add(spawBlue);
        spawBlue.setBounds(30, 10, 64, 90);
        jPanel1.add(spawnRed);
        spawnRed.setBounds(890, 500, 64, 90);
        jPanel1.add(house7);
        house7.setBounds(330, 40, 64, 90);
        jPanel1.add(house6);
        house6.setBounds(60, 300, 64, 90);
        jPanel1.add(house5);
        house5.setBounds(620, 350, 64, 90);
        jPanel1.add(house4);
        house4.setBounds(1020, 300, 64, 90);
        jPanel1.add(house3);
        house3.setBounds(740, 40, 64, 90);
        jPanel1.add(house2);
        house2.setBounds(550, 170, 64, 90);
        jPanel1.add(house1);
        house1.setBounds(310, 480, 64, 90);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 200, 73, 23);

        map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/map.jpg"))); // NOI18N
        map.setToolTipText("");
        map.setAlignmentY(0.0F);
        map.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        map.setName(""); // NOI18N
        jPanel1.add(map);
        map.setBounds(0, 0, 1095, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        spawnRed.setScore(0);
        Unity unit = new Unity();
        unit.setPlayer(playerBlue);
        jPanel1.add(unit);
        jPanel1.setComponentZOrder(unit, 0);
        unit.setLocation(100, 100);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.House house1;
    private component.House house2;
    private component.House house3;
    private component.House house4;
    private component.House house5;
    private component.House house6;
    private component.House house7;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel map;
    private component.House spawBlue;
    private component.House spawnRed;
    private component.UnitiesProgessBar unitiesProgessBar2;
    // End of variables declaration//GEN-END:variables
}
