/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mushroomwarjava;

import java.awt.Toolkit;

/**
 * Fenêtre de configuration de la partie
 * 
 * @author Jonathan
 */
public class gameSetting extends javax.swing.JFrame {

    /**
     * Instance de la partie
     */
    private gameUI game;
    
    /**
     * Equipe selectionner par le joueur
     */
    private int teamSelected;
    
    /**
     * Creates new form gameSetting
     */
    public gameSetting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioTeam = new javax.swing.ButtonGroup();
        copyright = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        redTeam = new javax.swing.JRadioButton();
        blueTeam = new javax.swing.JRadioButton();
        nameSelection = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mushroom War Java Project");
        setBackground(new java.awt.Color(102, 102, 102));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mushroomwarjava/assets/mushroomWarIcon.gif")));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        copyright.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        copyright.setText("©Copyright LaMache");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisis ton équipe !");

        radioTeam.add(redTeam);
        redTeam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        redTeam.setForeground(new java.awt.Color(255, 255, 255));
        redTeam.setToolTipText("");
        redTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/redMushroom.png"))); // NOI18N
        redTeam.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/redMushroomActive.png"))); // NOI18N
        redTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamActionPerformed(evt);
            }
        });

        radioTeam.add(blueTeam);
        blueTeam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        blueTeam.setForeground(new java.awt.Color(255, 255, 255));
        blueTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/blueMushroom.png"))); // NOI18N
        blueTeam.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/blueMushroomActive.png"))); // NOI18N
        blueTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTeamActionPerformed(evt);
            }
        });

        nameSelection.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nameSelectionCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Quel est ton nom ?");

        Start.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Start.setText("Start !");
        Start.setEnabled(false);
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameSelection))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(redTeam)
                                .addGap(78, 78, 78)
                                .addComponent(blueTeam)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redTeam)
                    .addComponent(blueTeam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Start)
                .addGap(18, 18, 18)
                .addComponent(copyright)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Evenement lors du click sur Start
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        this.game = new gameUI(); // Création d'une partie
        this.game.setActionPlayer(new Player(this.teamSelected, nameSelection.getText()));  // Préparation de la partie
        this.setVisible(false); // On cache la fenêtre de configuration
        this.game.setVisible(true); // On affiche le jeu
        this.game.gameBegin();  // On lance la partie ( permet nottament de gérer les différents threads dont l'IA )
    }//GEN-LAST:event_StartActionPerformed

    // Evenement lors du click sur le champignon Bleu ( choix de l'équipe )
    private void blueTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTeamActionPerformed
        this.teamSelected = Player.TEAM_BLUE;   // on choisit l'équipe bleu
        this.isDisabled();  // Verification des conditions
    }//GEN-LAST:event_blueTeamActionPerformed

    // Evenement lors du click sur le champignon Rouge
    private void redTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamActionPerformed
        this.teamSelected = Player.TEAM_RED;    // on choisit l'équipe rouge
        this.isDisabled();  // Verification des conditions
    }//GEN-LAST:event_redTeamActionPerformed

    // Evenement lors de la saisie clavier du nom
    private void nameSelectionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nameSelectionCaretUpdate
        this.isDisabled();  // Verification des conditions
    }//GEN-LAST:event_nameSelectionCaretUpdate

    /*
    * Méthode appelé pour verifié les conditions de sélection de la fenêtre
    * Ex: Est ce qu'une équipe a été selectionné ?
    */
    private void isDisabled() {
        /*
        * Si un caractère a été saisie et qu'une équipe a été selectionné passe à true
        */
        if(!nameSelection.getText().equals("") && (redTeam.isSelected() || blueTeam.isSelected())) {
            Start.setEnabled(true);
        } else {
            Start.setEnabled(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Start;
    private javax.swing.JRadioButton blueTeam;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameSelection;
    private javax.swing.ButtonGroup radioTeam;
    private javax.swing.JRadioButton redTeam;
    // End of variables declaration//GEN-END:variables
}
