/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import mushroomwarjava.Player;

/**
 *
 * @author Jonathan Germain
 */
public class House extends javax.swing.JPanel {

    private Player currentPlayer;
    /**
     * Creates new form House
     */
    public House() {
        initComponents();
    }
    
    public void setScore(int score) {
        this.countHouse.setText(score + "");
        if(score > 0) {
            if(this.currentPlayer.getTeam() == Player.TEAM_BLUE) {
                mushroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/blueMushroom.png"))); // NOI18N
            }
            if(this.currentPlayer.getTeam() == Player.TEAM_RED) {
                mushroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/redMushroom.png"))); // NOI18N
            }
        } else {
            mushroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/emptyMushroom.png"))); // NOI18N
        }
        mushroom.repaint();
    }
    
    public void setPlayer(Player p) {
        this.currentPlayer = p;
        this.setScore(p.getUnities());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countHouse = new javax.swing.JLabel();
        mushroom = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(64, 90));
        setMinimumSize(new java.awt.Dimension(64, 90));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(64, 90));
        setLayout(new java.awt.BorderLayout(0, 10));

        countHouse.setBackground(new java.awt.Color(255, 255, 255));
        countHouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countHouse.setText("0");
        countHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        countHouse.setMaximumSize(new java.awt.Dimension(6, 20));
        countHouse.setMinimumSize(new java.awt.Dimension(6, 20));
        countHouse.setOpaque(true);
        countHouse.setPreferredSize(new java.awt.Dimension(6, 20));
        add(countHouse, java.awt.BorderLayout.PAGE_START);

        mushroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mushroomwarjava/assets/emptyMushroom.png"))); // NOI18N
        mushroom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mushroom.setMaximumSize(new java.awt.Dimension(64, 90));
        mushroom.setMinimumSize(new java.awt.Dimension(64, 90));
        mushroom.setPreferredSize(new java.awt.Dimension(64, 90));
        add(mushroom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countHouse;
    private javax.swing.JLabel mushroom;
    // End of variables declaration//GEN-END:variables
}
