/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import mushroomwarjava.Player;

/**
 * Composant graphique gérant la bar de progression du jeu
 * @author Jonathan Germain
 */
public class UnitiesProgessBar extends biprogressbar.BiProgressBar {
    
    /**
     * nombre d'unitées rouge
     */
    private int redUnit;
    
    /**
     * nombre d'unité bleu
     */
    private int blueUnit;
    
    /**
     * nombre d'unité total en jeu
     */
    private int totalUnit;
    
    /**
     * Creates new form NewJPanel
     */
    public UnitiesProgessBar() {
        initComponents();
    }
    
    /**
     * Permet de mettre à jour la bar de progression
     * @param i nombre d'unité bleu
     * @param total total d'unité calculé
     */
    public void refreshProgressBar(int i, int total) {
        this.blueUnit = i;
        this.clear2();
        this.addXElementBar2(total-i);
        this.redUnit = total - i;
        this.clear1();
        this.addXElementBar1(i);
        this.totalUnit = total;
    }
    
    /**
     * Test l'état de la partie
     * @return Vrai si les deux joueur possèdent encore une unité
     */
    public boolean isTwoPlayerAlive() {
        return (this.blueUnit == 0 || this.redUnit == 0);
    }

    /**
     * Permet de déterminer la couleur de l'équipe victorieuse
     * @return Equipe gagnante
     */
    public int whoWin() {
        int winner = -1;
        if(this.redUnit == 0) {
            winner = Player.TEAM_BLUE;
        } else {
            winner = Player.TEAM_RED;
        }
        return winner;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();

        setColor1(java.awt.Color.blue);
        setColor2(java.awt.Color.red);
        setLayout(new java.awt.BorderLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 0, 0));
        jProgressBar1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(50);
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setOpaque(true);
        add(jProgressBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
