/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import java.awt.Color;
import java.awt.Graphics;
import mushroomwarjava.Player;

/**
 *
 * @author Jonathan Germain
 */
public class Unity extends javax.swing.JPanel {

    private Player currentPlayer;
    /**
     * Creates new form Unity
     */
    public Unity() {
        initComponents();
        setSize(15, 15);
    }
    
    public Unity(Player thePlayer) {
        initComponents();
        setSize(15, 15);
        this.setPlayer(thePlayer);
    }

    @Override
    protected void paintComponent(Graphics g) {
        if(this.currentPlayer != null) {
            Color teamColor = ((this.currentPlayer.getTeam() == Player.TEAM_RED) ? Color.RED : Color.BLUE);
            g.setColor(Color.BLACK);
            g.fillOval(0, 0, 15, 15);
            g.setColor(teamColor);
            g.fillOval(0, 0, 12, 12);            
        }
    }

    public void setPlayer(Player p) {
        this.currentPlayer = p;
        this.repaint();
    }
    
    public Player getPlayer() {
        return this.currentPlayer;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(15, 15));
        setMinimumSize(new java.awt.Dimension(15, 15));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
